### PR TITLE
Add docs as a seperate build step on travis

### PR DESCRIPTION
**Pull request by saschatimme**
This is to avoid #97 again. This let's travis fail if it is not possible to build the docs.

### CODE REVIEW

**Comment by saschatimme** [comment]
@blegat there is the following warning in the Documenter log
```
 Warning: repo github.com/blegat/MultivariatePolynomials.jl.git does not match JuliaAlgebra/MultivariatePolynomials.jl
```

Can it be that the private key is still setup for your private repo?

**Comment by blegat** [comment]
Yes that's plausible. I am on my phone now but I should check

**Comment by saschatimme** [comment]
@blegat I will merge this for now, since it still works with the other key

**Comment by blegat** [comment]
It might be fixed by 53f71434770583a7c4341efdb91dd45f78771919

**Comment by saschatimme** [comment]
Oh stupid me 🙈

**Pull request merged**
