### PR TITLE
Towards v0.7 compatibility

### PR DESCRIPTION
**Pull request by rdeits**
@blegat this is the same as #70 but using the `fix-0.7` branch on this repo instead of my fork, which should make it easier to collaborate.

### CODE REVIEW

**Comment by blegat** [comment]
I don't get the error mentionned in https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/70#issuecomment-370462269 when running tests of TypedPolynomials with MP tests uncommented

**Comment by blegat** [comment]
@rdeits I found a MWE
```julia
julia> using TypedPolynomials
julia> @polyvar x
julia> p = x^2 - x
julia> P = typeof(p)
Polynomial{Int64,Term{Int64,Monomial{(x,),1}},Array{Term{Int64,Monomial{(x,),1}},1}}
julia> P(p)
ERROR: MethodError: no method matching zero(::Type{Array{Term{Int64,Monomial{(x,),1}},1}})
Closest candidates are:
  zero(::Type{LibGit2.GitHash}) at /home/blegat/git/julia/usr/share/julia/site/v0.7/LibGit2/src/oid.jl:210
  zero(::Type{Pkg.Resolve.VersionWeights.VWPreBuildItem}) at /home/blegat/git/julia/usr/share/julia/site/v0.7/Pkg/src/resolve/versionweight.jl:80
  zero(::Type{Pkg.Resolve.VersionWeights.VWPreBuild}) at /home/blegat/git/julia/usr/share/julia/site/v0.7/Pkg/src/resolve/versionweight.jl:116
  ...
Stacktrace:
 [1] convert(::Type{Array{Term{Int64,Monomial{(x,),1}},1}}, ::Polynomial{Int64,Term{Int64,Monomial{(x,),1}},Array{Term{Int64,Monomial{(x,),1}},1}}) at /home/blegat/.julia/v0.7/MultivariatePolynomials/src/conversion.jl:17
 [2] Polynomial{Int64,Term{Int64,Monomial{(x,),1}},Array{Term{Int64,Monomial{(x,),1}},1}}(::Polynomial{Int64,Term{Int64,Monomial{(x,),1}},Array{Term{Int64,Monomial{(x,),1}},1}}) at /home/blegat/.julia/v0.7/TypedPolynomials/src/types.jl:65
 [3] top-level scope
```

**Comment by rdeits** [comment]
Ah, excellent. That looks like something I can fix in TypedPolynomials.

**Comment by blegat** [comment]
Yes, you have no constructor with types specified so it simply fallbacks to the default constructor and try to convert the polynomial to the `terms` field.

**Comment by blegat** [comment]
On DynamicPolynomials, I have this
https://github.com/JuliaAlgebra/DynamicPolynomials.jl/blob/382b29ae4d077bc7a7e719e4af2922e74a1a2ee5/src/poly.jl#L43-L45

**Comment by rdeits** [comment]
Ok, resolved in https://github.com/JuliaAlgebra/TypedPolynomials.jl/pull/39

**Pull request merged**
